import React ,{useState,useEffect}from 'react'
import CheckoutProduct from '../components/CheckoutProduct';
import { useSelector } from 'react-redux';
import Subtotal from '@/components/Subtotal';
import { useStateValue } from '@/Store/Store';
import { useRouter } from 'next/router';


function Checkout() { 
  const [{basket} ] = useStateValue();
 const router=useRouter()



 const add =()=>{
  router.push('/')
    }


  return (
<div className='b bg-slate-800'>


<div
      initial={{ opacity: 0 }}
      whileInView={{ opacity: 1 }}
      viewport={{ once: true }}
      className="bg-gray-100"
    >
      <div>
        <button onClick={add} className='u uppercase font-bold text-cyan-400'>Amazon Clone Amazon</button>
        <span name="description" content="Generated by create next app" />
        <span name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href=".png"
        />
      </div>
      
      <main className="lg:flex max-w-screen-2xl mx-auto">
        <div className="flex-grow m-5 shadow-sm">
          <img
            src="/soon.jpg"
            width={700}
            height={300}
            
            className='w-full h-60 '
          />

          <div className="flex flex-col  ">
            <button className="text-3xl border-b pb-4">
            {basket.length === 0
                ? "Your Amazon Basket is empty"
                : "Your Shopping Basket"}
            </button>
            <div className="flex flex-col   shadow-md w-30">
           {basket.map((produt) => (   
        
       <CheckoutProduct className=' flex bg-black' 
       key={produt.id}
     name={produt.name}
     price={produt.price}
     
     image={produt.image}
     rating={produt.rating}
      ></CheckoutProduct>
))}
           </div>
           
          </div>
        </div>
        <div className="flex  hover:bg-yellow-200 p-10 shadow-md w-50">
           
            
       
          
            
             
            
          
         <Subtotal/>
        
            
          
        
        </div>
      </main>
    </div>
    
    </div>
  );
};

export default Checkout