export default {
    products: [
      
      {
        _id: '2',
        name: 'Fit Shirt',
        category: 'Shirts',
        image: '/images/p3.jpg',
        price: 50,
        brand: ' Nike',
        rating:[5],
        numReviews: 5,
        quantity: 1,
      },
      {
        _id: '3',
        name: 'slim t-shirt',
        category: 'Pants',
        image: '/images/p1.jpg',
        price:90,
        brand: ' Nike',
        rating:[5],
        numReviews: 8,
        quantity: 1,
      }, {
        _id: '4',
        name: 'mark All t-shirt',
        category: 'Pants',
        image: '/images/p2.jpg',
        price: 80,
        brand: ' Nike',
        rating: 5,
        numReviews: 8,
        quantity: 1,
      },

      {
        _id: '3',
        name: 'hot t-shirt',
        category: 'Pants',
        image: '/images/p3.jpg',
        price: 70,
        brand: ' Nike',
        rating: [5],
        numReviews: 8,
        quantity: 1,
      }, {
        _id: '4',
        name: 'dark All t-shirt',
        category: 'Pants',
        image: '/images/d3.jpg',
        price: 30,
        brand: ' Nike',
        rating: 5,
        numReviews: 8,
        quantity: 1,
      },

      {
        _id: '3',
        name: 'small t-shirt',
        category: 'Pants',
        image: '/images/d1.jpg',
        price: 40,
        brand: ' Nike',
        rating: [5],
        numReviews: 8,
        quantity: 1,
      }, {
        _id: '4',
        name: 'long All t-shirt',
        category: 'Pants',
        image: '/images/d2.jpg',
        price: 70,
        brand: ' Nike',
        rating: 5,
        numReviews: 8,
        quantity: 1,
      },

      {
        _id: '1',
        name: 'color Shirt',
        category: 'Shirts',
        image: '/images/d3.jpg',
        price: 60,
        brand: ' Nike',
        rating: [5],
        numReviews: 10,
        quantity: 1,
      },
    ]
  }